/* ============================================================
   SATORI — background.js (merged extension)
   Single background script shared by sidebar + newtab.
   All storage writes from either page flow through here,
   and browser.theme.update() fires correctly for both.
   ============================================================ */

const CHROME_THEMES = {
  sakura: {
    dark: {
      frame:                        '#0d0a12',
      frame_inactive:               '#0a0810',
      tab_background_text:          '#c4a8d4',
      tab_text:                     '#f0e6ff',
      tab_line:                     '#e8609a',
      tab_loading:                  '#e8609a',
      tab_selected:                 '#1e1530',
      toolbar:                      '#150f1e',
      toolbar_text:                 '#f0e6ff',
      toolbar_field:                '#0d0a12',
      toolbar_field_text:           '#f0e6ff',
      toolbar_field_border:         '#3a2050',
      toolbar_field_focus:          '#1e1530',
      toolbar_field_border_focus:   '#e8609a',
      toolbar_top_separator:        '#e8609a',
      toolbar_bottom_separator:     '#2a1840',
      toolbar_vertical_separator:   '#2a1840',
      icons:                        '#c4a8d4',
      icons_attention:              '#e8609a',
      button_background_hover:      '#1e1530',
      button_background_active:     '#2a1840',
      sidebar:                      '#100d18',
      sidebar_text:                 '#f0e6ff',
      sidebar_border:               '#2a1840',
      sidebar_highlight:            '#e8609a',
      sidebar_highlight_text:       '#f0e6ff',
      popup:                        '#150f1e',
      popup_text:                   '#f0e6ff',
      popup_border:                 '#3a2050',
      popup_highlight:              '#e8609a',
      popup_highlight_text:         '#f0e6ff',
    },
    light: {
      frame:                        '#f5e8f0',
      frame_inactive:               '#fdf6f9',
      tab_background_text:          '#6b4070',
      tab_text:                     '#2a1a2e',
      tab_line:                     '#c0547e',
      tab_loading:                  '#c0547e',
      tab_selected:                 '#fdf6f9',
      toolbar:                      '#fdf6f9',
      toolbar_text:                 '#2a1a2e',
      toolbar_field:                '#ffffff',
      toolbar_field_text:           '#2a1a2e',
      toolbar_field_border:         '#dcc0d0',
      toolbar_field_focus:          '#ffffff',
      toolbar_field_border_focus:   '#c0547e',
      toolbar_top_separator:        '#dcc0d0',
      toolbar_bottom_separator:     '#ecd8e4',
      toolbar_vertical_separator:   '#ecd8e4',
      icons:                        '#903858',
      icons_attention:              '#c0547e',
      button_background_hover:      '#f5e8f0',
      button_background_active:     '#ecdce8',
      sidebar:                      '#fdf6f9',
      sidebar_text:                 '#2a1a2e',
      sidebar_border:               '#dcc0d0',
      sidebar_highlight:            '#c0547e',
      sidebar_highlight_text:       '#ffffff',
      popup:                        '#fdf6f9',
      popup_text:                   '#2a1a2e',
      popup_border:                 '#dcc0d0',
      popup_highlight:              '#c0547e',
      popup_highlight_text:         '#ffffff',
    },
  },
  cyberpunk: {
    dark: {
      frame:                        '#080c14',
      frame_inactive:               '#050810',
      tab_background_text:          '#7ac8d8',
      tab_text:                     '#e0f8ff',
      tab_line:                     '#00f0ff',
      tab_loading:                  '#ff0099',
      tab_selected:                 '#111828',
      toolbar:                      '#0d1220',
      toolbar_text:                 '#e0f8ff',
      toolbar_field:                '#080c14',
      toolbar_field_text:           '#e0f8ff',
      toolbar_field_border:         '#1a2e48',
      toolbar_field_focus:          '#111828',
      toolbar_field_border_focus:   '#00f0ff',
      toolbar_top_separator:        '#00f0ff',
      toolbar_bottom_separator:     '#1a2e48',
      toolbar_vertical_separator:   '#1a2e48',
      icons:                        '#7ac8d8',
      icons_attention:              '#00f0ff',
      button_background_hover:      '#111828',
      button_background_active:     '#1a2e48',
      sidebar:                      '#0a0e18',
      sidebar_text:                 '#e0f8ff',
      sidebar_border:               '#1a2e48',
      sidebar_highlight:            '#00f0ff',
      sidebar_highlight_text:       '#080c14',
      popup:                        '#0d1220',
      popup_text:                   '#e0f8ff',
      popup_border:                 '#1a2e48',
      popup_highlight:              '#00f0ff',
      popup_highlight_text:         '#080c14',
    },
    light: {
      frame:                        '#cce8f5',
      frame_inactive:               '#e0f0f8',
      tab_background_text:          '#206080',
      tab_text:                     '#0a2030',
      tab_line:                     '#0088aa',
      tab_loading:                  '#cc0077',
      tab_selected:                 '#f0f8ff',
      toolbar:                      '#f0f8ff',
      toolbar_text:                 '#0a2030',
      toolbar_field:                '#ffffff',
      toolbar_field_text:           '#0a2030',
      toolbar_field_border:         '#a0d0e8',
      toolbar_field_focus:          '#ffffff',
      toolbar_field_border_focus:   '#0088aa',
      toolbar_top_separator:        '#a0d0e8',
      toolbar_bottom_separator:     '#c8e8f5',
      toolbar_vertical_separator:   '#c8e8f5',
      icons:                        '#006688',
      icons_attention:              '#0088aa',
      button_background_hover:      '#e0f0f8',
      button_background_active:     '#cce8f5',
      sidebar:                      '#f0f8ff',
      sidebar_text:                 '#0a2030',
      sidebar_border:               '#a0d0e8',
      sidebar_highlight:            '#0088aa',
      sidebar_highlight_text:       '#ffffff',
      popup:                        '#f0f8ff',
      popup_text:                   '#0a2030',
      popup_border:                 '#a0d0e8',
      popup_highlight:              '#0088aa',
      popup_highlight_text:         '#ffffff',
    },
  },
  shonen: {
    dark: {
      frame:                        '#0d0d0d',
      frame_inactive:               '#0a0a0a',
      tab_background_text:          '#e8b060',
      tab_text:                     '#fff5e0',
      tab_line:                     '#ff6600',
      tab_loading:                  '#ffdd00',
      tab_selected:                 '#1a1400',
      toolbar:                      '#131313',
      toolbar_text:                 '#fff5e0',
      toolbar_field:                '#0d0d0d',
      toolbar_field_text:           '#fff5e0',
      toolbar_field_border:         '#2a2200',
      toolbar_field_focus:          '#1a1400',
      toolbar_field_border_focus:   '#ff6600',
      toolbar_top_separator:        '#ff6600',
      toolbar_bottom_separator:     '#2a2200',
      toolbar_vertical_separator:   '#2a2200',
      icons:                        '#e8b060',
      icons_attention:              '#ffdd00',
      button_background_hover:      '#1a1400',
      button_background_active:     '#2a2200',
      sidebar:                      '#0f0f0f',
      sidebar_text:                 '#fff5e0',
      sidebar_border:               '#2a2200',
      sidebar_highlight:            '#ff6600',
      sidebar_highlight_text:       '#fff5e0',
      popup:                        '#131313',
      popup_text:                   '#fff5e0',
      popup_border:                 '#2a2200',
      popup_highlight:              '#ff6600',
      popup_highlight_text:         '#fff5e0',
    },
    light: {
      frame:                        '#ffe5c0',
      frame_inactive:               '#fff0d8',
      tab_background_text:          '#804020',
      tab_text:                     '#1a0a00',
      tab_line:                     '#cc4400',
      tab_loading:                  '#ffdd00',
      tab_selected:                 '#fffaf0',
      toolbar:                      '#fffaf0',
      toolbar_text:                 '#1a0a00',
      toolbar_field:                '#ffffff',
      toolbar_field_text:           '#1a0a00',
      toolbar_field_border:         '#f0c878',
      toolbar_field_focus:          '#ffffff',
      toolbar_field_border_focus:   '#cc4400',
      toolbar_top_separator:        '#f0c878',
      toolbar_bottom_separator:     '#ffe0b0',
      toolbar_vertical_separator:   '#ffe0b0',
      icons:                        '#993300',
      icons_attention:              '#cc4400',
      button_background_hover:      '#fff0d8',
      button_background_active:     '#ffe5c0',
      sidebar:                      '#fffaf0',
      sidebar_text:                 '#1a0a00',
      sidebar_border:               '#f0c878',
      sidebar_highlight:            '#cc4400',
      sidebar_highlight_text:       '#ffffff',
      popup:                        '#fffaf0',
      popup_text:                   '#1a0a00',
      popup_border:                 '#f0c878',
      popup_highlight:              '#cc4400',
      popup_highlight_text:         '#ffffff',
    },
  },
  isekai: {
    dark: {
      frame:                        '#0a0d18',
      frame_inactive:               '#080a14',
      tab_background_text:          '#b0a0e8',
      tab_text:                     '#ece8ff',
      tab_line:                     '#8878ff',
      tab_loading:                  '#c8b8ff',
      tab_selected:                 '#141830',
      toolbar:                      '#0e1222',
      toolbar_text:                 '#ece8ff',
      toolbar_field:                '#0a0d18',
      toolbar_field_text:           '#ece8ff',
      toolbar_field_border:         '#2a2450',
      toolbar_field_focus:          '#141830',
      toolbar_field_border_focus:   '#8878ff',
      toolbar_top_separator:        '#8878ff',
      toolbar_bottom_separator:     '#2a2450',
      toolbar_vertical_separator:   '#2a2450',
      icons:                        '#b0a0e8',
      icons_attention:              '#8878ff',
      button_background_hover:      '#141830',
      button_background_active:     '#1e1a40',
      sidebar:                      '#0c0f1c',
      sidebar_text:                 '#ece8ff',
      sidebar_border:               '#2a2450',
      sidebar_highlight:            '#8878ff',
      sidebar_highlight_text:       '#ece8ff',
      popup:                        '#0e1222',
      popup_text:                   '#ece8ff',
      popup_border:                 '#2a2450',
      popup_highlight:              '#8878ff',
      popup_highlight_text:         '#ece8ff',
    },
    light: {
      frame:                        '#e0d8ff',
      frame_inactive:               '#ede8ff',
      tab_background_text:          '#403880',
      tab_text:                     '#0a0820',
      tab_line:                     '#5545cc',
      tab_loading:                  '#7b6fff',
      tab_selected:                 '#f5f3ff',
      toolbar:                      '#f5f3ff',
      toolbar_text:                 '#0a0820',
      toolbar_field:                '#ffffff',
      toolbar_field_text:           '#0a0820',
      toolbar_field_border:         '#c0b0f0',
      toolbar_field_focus:          '#ffffff',
      toolbar_field_border_focus:   '#5545cc',
      toolbar_top_separator:        '#c0b0f0',
      toolbar_bottom_separator:     '#dcd4ff',
      toolbar_vertical_separator:   '#dcd4ff',
      icons:                        '#3830aa',
      icons_attention:              '#5545cc',
      button_background_hover:      '#ede8ff',
      button_background_active:     '#e0d8ff',
      sidebar:                      '#f5f3ff',
      sidebar_text:                 '#0a0820',
      sidebar_border:               '#c0b0f0',
      sidebar_highlight:            '#5545cc',
      sidebar_highlight_text:       '#ffffff',
      popup:                        '#f5f3ff',
      popup_text:                   '#0a0820',
      popup_border:                 '#c0b0f0',
      popup_highlight:              '#5545cc',
      popup_highlight_text:         '#ffffff',
    },
  },
};

function applyChromeTheme(themeName, lightMode) {
  const def = CHROME_THEMES[themeName];
  if (!def) return;
  browser.theme.update({ colors: lightMode ? def.light : def.dark });
}

browser.storage.onChanged.addListener((changes, area) => {
  if (area !== 'local') return;
  browser.storage.local.get(['satori_theme', 'light_mode']).then(r => {
    applyChromeTheme(r.satori_theme || 'sakura', r.light_mode === 'light');
  });
});

browser.storage.local.get(['satori_theme', 'light_mode']).then(r => {
  applyChromeTheme(r.satori_theme || 'sakura', r.light_mode === 'light');
});
